name: test simple actions
on:
  repository_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-action:
    runs-on: ubuntu-latest
    steps:
    # A step will be added automatically to build the referenced docker action
    - uses: h10s/docker-action@master
      with:
        who-to-greet: "bobby tables"

  javascript-action:
    runs-on: ubuntu-latest
    steps:
    - uses: h10s/javascript-action@master
      with:
        who-to-greet: "bobby tables"

  pre-post-javascript-action:
    runs-on: ubuntu-latest
    steps:
    - uses: h10s/pre-post-javascript-action@master
      with:
        who-to-greet: "bobby tables"

# fin
